# MoriMeta product workspace (Phase 1a foundation: parts that do not depend on pending decisions).
# Licensed GPL-3.0-or-later (D-1, 2026-09-27; see LICENSE). Dependencies stay permissive and
# GPL-3.0-compatible.
[workspace]
resolver = "3"
members = ["crates/mm-cli","crates/mm-core","crates/mm-domain", "crates/mm-exiftool", "crates/mm-fs", "crates/mm-store"]
exclude = ["research"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
publish = false
version = "0.0.0"
license = "GPL-3.0-or-later"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
