// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One table row: 30 text fields, like the Library row summary (ARCHITECTURE §8.3, ~1 KB/row).
 */
export type Row = { id: number, fields: Array<string>, };
