[package]
name = "mm-exiftool"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
getrandom = "0.4.3"
serde_json = "1.0.151"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_JobObjects", "Win32_System_Threading", "Win32_Security"] }

[lints]
workspace = true
